### PR TITLE
Use React.cloneElement to keep refs

### PR DESCRIPTION
**Pull request by kgunbin**
Using `React.cloneElement` instead of `React.addons.cloneWithProps` to keep elements' refs
Addressing the issue https://github.com/jsdf/react-layout/issues/9

### CODE REVIEW

**Comment by jsdf** [comment]
Thanks! published to npm as v1.1.0

**Comment by kgunbin** [comment]
Thanks, but it is not available ATM.

```
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/node/5.5.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.5.0
npm ERR! npm  v3.5.3

npm ERR! No compatible version found: react-layout@1.1.0
npm ERR! Valid install targets:
npm ERR! 0.2.0, 0.1.6, 0.1.5, 0.1.2, 0.1.1, 0.1.0
```

**Comment by jsdf** [comment]
whoops! it's actually published now

**Comment by kgunbin** [comment]
:+1:

**Pull request merged**
